version : '3.5'

services :
  kotlin-restful-api:
    container_name: kotlin-restful-api
    image: kotlin-restful-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_URL: jdbc:postgresql://kotlin-restful-api-postgres:5432/restful-api
  kotlin-restful-api-postgres :
    container_name: "kotlin-restful-api-postgres"
    image: postgres
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restful-api